package com.example.dto;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * VEHICLE 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class DetailCount {
	
	String vName;
	String vNameCnt;
	
/*	//출발지 
	String vstartName;
	Integer vstartNameCount;
	
	//도착지
	String vendName;
	Integer vendNameCount;
	
	//교통수단번호
	String vehicleNum;
	Integer vehicleNumCount;
*/
	
}
