package com.example.dto;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ROUTE 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Route implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ROUTE_ID. */
	private Integer routeId;

	/** ROUTE_NAME. */
	private String routeName;

	/** START_LAT. */
	private String startLat;

	/** START_LNG. */
	private String startLng;

	/** START_ADDRESS. */
	private String startAddress;

	/** ARRIVE_LAT. */
	private String arriveLat;

	/** ARRIVE_LNG. */
	private String arriveLng;

	/** ARRIVE_ADDRESS. */
	private String arriveAddress;

	/** DISTANCE. */
	private String distance;

	/** TIME. */
	private String time;

	/** STEP 목록. */
	private Set<Step> stepSet;

}
