package com.example.dto;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * STEP 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Step implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** STEP_ID. */
	private Integer stepId;

	/** ROUTE. */
	private Route route;

	/** VMODE. */
	private String vmode;

	/** VEHICLE_INFO. */
	private String vehicleInfo;

	/** STEP_NAME. */
	private String stepName;

	/** START_LAT. */
	private String startLat;

	/** START_LNG. */
	private String startLng;

	/** END_LAT. */
	private String endLat;

	/** END_LNG. */
	private String endLng;

	/** ROUTE_DISTANCE. */
	private String routeDistance;

	/** ROUTE_TIME. */
	private String routeTime;

	/** SEQ. */
	private Integer seq;

	/** VEHICLE 목록. */
	private Set<Vehicle> vehicleSet;

	/**
	 * 생성자.
	 */
	public Step() {
		this.vehicleSet = new HashSet<Vehicle>();
	}

	/**
	 * STEP_ID을 설정합니다..
	 * 
	 * @param stepId
	 *            STEP_ID
	 */
	public void setStepId(Integer stepId) {
		this.stepId = stepId;
	}

	/**
	 * STEP_ID을 가져옵니다..
	 * 
	 * @return STEP_ID
	 */
	public Integer getStepId() {
		return this.stepId;
	}

	/**
	 * ROUTE을 설정합니다..
	 * 
	 * @param route
	 *            ROUTE
	 */
	public void setRoute(Route route) {
		this.route = route;
	}

	/**
	 * ROUTE을 가져옵니다..
	 * 
	 * @return ROUTE
	 */
	public Route getRoute() {
		return this.route;
	}

	/**
	 * VMODE을 설정합니다..
	 * 
	 * @param vmode
	 *            VMODE
	 */
	public void setVmode(String vmode) {
		this.vmode = vmode;
	}

	/**
	 * VMODE을 가져옵니다..
	 * 
	 * @return VMODE
	 */
	public String getVmode() {
		return this.vmode;
	}

	/**
	 * VEHICLE_INFO을 설정합니다..
	 * 
	 * @param vehicleInfo
	 *            VEHICLE_INFO
	 */
	public void setVehicleInfo(String vehicleInfo) {
		this.vehicleInfo = vehicleInfo;
	}

	/**
	 * VEHICLE_INFO을 가져옵니다..
	 * 
	 * @return VEHICLE_INFO
	 */
	public String getVehicleInfo() {
		return this.vehicleInfo;
	}

	/**
	 * STEP_NAME을 설정합니다..
	 * 
	 * @param stepName
	 *            STEP_NAME
	 */
	public void setStepName(String stepName) {
		this.stepName = stepName;
	}

	/**
	 * STEP_NAME을 가져옵니다..
	 * 
	 * @return STEP_NAME
	 */
	public String getStepName() {
		return this.stepName;
	}

	/**
	 * START_LAT을 설정합니다..
	 * 
	 * @param startLat
	 *            START_LAT
	 */
	public void setStartLat(String startLat) {
		this.startLat = startLat;
	}

	/**
	 * START_LAT을 가져옵니다..
	 * 
	 * @return START_LAT
	 */
	public String getStartLat() {
		return this.startLat;
	}

	/**
	 * START_LNG을 설정합니다..
	 * 
	 * @param startLng
	 *            START_LNG
	 */
	public void setStartLng(String startLng) {
		this.startLng = startLng;
	}

	/**
	 * START_LNG을 가져옵니다..
	 * 
	 * @return START_LNG
	 */
	public String getStartLng() {
		return this.startLng;
	}

	/**
	 * END_LAT을 설정합니다..
	 * 
	 * @param endLat
	 *            END_LAT
	 */
	public void setEndLat(String endLat) {
		this.endLat = endLat;
	}

	/**
	 * END_LAT을 가져옵니다..
	 * 
	 * @return END_LAT
	 */
	public String getEndLat() {
		return this.endLat;
	}

	/**
	 * END_LNG을 설정합니다..
	 * 
	 * @param endLng
	 *            END_LNG
	 */
	public void setEndLng(String endLng) {
		this.endLng = endLng;
	}

	/**
	 * END_LNG을 가져옵니다..
	 * 
	 * @return END_LNG
	 */
	public String getEndLng() {
		return this.endLng;
	}

	/**
	 * ROUTE_DISTANCE을 설정합니다..
	 * 
	 * @param routeDistance
	 *            ROUTE_DISTANCE
	 */
	public void setRouteDistance(String routeDistance) {
		this.routeDistance = routeDistance;
	}

	/**
	 * ROUTE_DISTANCE을 가져옵니다..
	 * 
	 * @return ROUTE_DISTANCE
	 */
	public String getRouteDistance() {
		return this.routeDistance;
	}

	/**
	 * ROUTE_TIME을 설정합니다..
	 * 
	 * @param routeTime
	 *            ROUTE_TIME
	 */
	public void setRouteTime(String routeTime) {
		this.routeTime = routeTime;
	}

	/**
	 * ROUTE_TIME을 가져옵니다..
	 * 
	 * @return ROUTE_TIME
	 */
	public String getRouteTime() {
		return this.routeTime;
	}

	/**
	 * SEQ을 설정합니다..
	 * 
	 * @param seq
	 *            SEQ
	 */
	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	/**
	 * SEQ을 가져옵니다..
	 * 
	 * @return SEQ
	 */
	public Integer getSeq() {
		return this.seq;
	}

	/**
	 * VEHICLE 목록을 설정합니다..
	 * 
	 * @param vehicleSet
	 *            VEHICLE 목록
	 */
	public void setVehicleSet(Set<Vehicle> vehicleSet) {
		this.vehicleSet = vehicleSet;
	}

	/**
	 * VEHICLE를 추가합니다..
	 * 
	 * @param vehicle
	 *            VEHICLE
	 */
	public void addVehicle(Vehicle vehicle) {
		this.vehicleSet.add(vehicle);
	}

	/**
	 * VEHICLE 목록을 가져옵니다..
	 * 
	 * @return VEHICLE 목록
	 */
	public Set<Vehicle> getVehicleSet() {
		return this.vehicleSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((stepId == null) ? 0 : stepId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Step other = (Step) obj;
		if (stepId == null) {
			if (other.stepId != null) {
				return false;
			}
		} else if (!stepId.equals(other.stepId)) {
			return false;
		}
		return true;
	}

}
