package com.example.dto;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * STEP 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Step implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** STEP_ID. */
	private Integer stepId;

	/** ROUTE. */
	private Route route;

	/** VMODE. */
	private String vmode;

	/** VEHICLE_INFO. */
	private String vehicleInfo;

	/** STEP_NAME. */
	private String stepName;

	/** START_LAT. */
	private String startLat;

	/** START_LNG. */
	private String startLng;

	/** END_LAT. */
	private String endLat;

	/** END_LNG. */
	private String endLng;

	/** ROUTE_DISTANCE. */
	private String routeDistance;

	/** ROUTE_TIME. */
	private String routeTime;

	/** SEQ. */
	private Integer seq;

	/** VEHICLE 목록. */
	private Set<Vehicle> vehicleSet;


}
