package com.example.dto;

import java.io.Serializable;

/**
 * VEHICLE 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Vehicle implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** VEHICLE_ID. */
	private Integer vehicleId;

	/** STEP. */
	private Step step;

	/** START_NAME. */
	private String startName;

	/** START_LAT. */
	private String startLat;

	/** START_LNG. */
	private String startLng;

	/** END_LAT. */
	private String endLat;

	/** END_LNG. */
	private String endLng;

	/** END_NAME. */
	private String endName;

	/** HEADSIGN. */
	private String headsign;

	/** VEHICLE_NAME. */
	private String vehicleName;

	/** VEHICLE_NUM. */
	private String vehicleNum;

	/** VEHICLE_MOVE. */
	private String vehicleMove;

	/**
	 * 생성자.
	 */
	public Vehicle() {
	}

	/**
	 * VEHICLE_ID을 설정합니다..
	 * 
	 * @param vehicleId
	 *            VEHICLE_ID
	 */
	public void setVehicleId(Integer vehicleId) {
		this.vehicleId = vehicleId;
	}

	/**
	 * VEHICLE_ID을 가져옵니다..
	 * 
	 * @return VEHICLE_ID
	 */
	public Integer getVehicleId() {
		return this.vehicleId;
	}

	/**
	 * STEP을 설정합니다..
	 * 
	 * @param step
	 *            STEP
	 */
	public void setStep(Step step) {
		this.step = step;
	}

	/**
	 * STEP을 가져옵니다..
	 * 
	 * @return STEP
	 */
	public Step getStep() {
		return this.step;
	}

	/**
	 * START_NAME을 설정합니다..
	 * 
	 * @param startName
	 *            START_NAME
	 */
	public void setStartName(String startName) {
		this.startName = startName;
	}

	/**
	 * START_NAME을 가져옵니다..
	 * 
	 * @return START_NAME
	 */
	public String getStartName() {
		return this.startName;
	}

	/**
	 * START_LAT을 설정합니다..
	 * 
	 * @param startLat
	 *            START_LAT
	 */
	public void setStartLat(String startLat) {
		this.startLat = startLat;
	}

	/**
	 * START_LAT을 가져옵니다..
	 * 
	 * @return START_LAT
	 */
	public String getStartLat() {
		return this.startLat;
	}

	/**
	 * START_LNG을 설정합니다..
	 * 
	 * @param startLng
	 *            START_LNG
	 */
	public void setStartLng(String startLng) {
		this.startLng = startLng;
	}

	/**
	 * START_LNG을 가져옵니다..
	 * 
	 * @return START_LNG
	 */
	public String getStartLng() {
		return this.startLng;
	}

	/**
	 * END_LAT을 설정합니다..
	 * 
	 * @param endLat
	 *            END_LAT
	 */
	public void setEndLat(String endLat) {
		this.endLat = endLat;
	}

	/**
	 * END_LAT을 가져옵니다..
	 * 
	 * @return END_LAT
	 */
	public String getEndLat() {
		return this.endLat;
	}

	/**
	 * END_LNG을 설정합니다..
	 * 
	 * @param endLng
	 *            END_LNG
	 */
	public void setEndLng(String endLng) {
		this.endLng = endLng;
	}

	/**
	 * END_LNG을 가져옵니다..
	 * 
	 * @return END_LNG
	 */
	public String getEndLng() {
		return this.endLng;
	}

	/**
	 * END_NAME을 설정합니다..
	 * 
	 * @param endName
	 *            END_NAME
	 */
	public void setEndName(String endName) {
		this.endName = endName;
	}

	/**
	 * END_NAME을 가져옵니다..
	 * 
	 * @return END_NAME
	 */
	public String getEndName() {
		return this.endName;
	}

	/**
	 * HEADSIGN을 설정합니다..
	 * 
	 * @param headsign
	 *            HEADSIGN
	 */
	public void setHeadsign(String headsign) {
		this.headsign = headsign;
	}

	/**
	 * HEADSIGN을 가져옵니다..
	 * 
	 * @return HEADSIGN
	 */
	public String getHeadsign() {
		return this.headsign;
	}

	/**
	 * VEHICLE_NAME을 설정합니다..
	 * 
	 * @param vehicleName
	 *            VEHICLE_NAME
	 */
	public void setVehicleName(String vehicleName) {
		this.vehicleName = vehicleName;
	}

	/**
	 * VEHICLE_NAME을 가져옵니다..
	 * 
	 * @return VEHICLE_NAME
	 */
	public String getVehicleName() {
		return this.vehicleName;
	}

	/**
	 * VEHICLE_NUM을 설정합니다..
	 * 
	 * @param vehicleNum
	 *            VEHICLE_NUM
	 */
	public void setVehicleNum(String vehicleNum) {
		this.vehicleNum = vehicleNum;
	}

	/**
	 * VEHICLE_NUM을 가져옵니다..
	 * 
	 * @return VEHICLE_NUM
	 */
	public String getVehicleNum() {
		return this.vehicleNum;
	}

	/**
	 * VEHICLE_MOVE을 설정합니다..
	 * 
	 * @param vehicleMove
	 *            VEHICLE_MOVE
	 */
	public void setVehicleMove(String vehicleMove) {
		this.vehicleMove = vehicleMove;
	}

	/**
	 * VEHICLE_MOVE을 가져옵니다..
	 * 
	 * @return VEHICLE_MOVE
	 */
	public String getVehicleMove() {
		return this.vehicleMove;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((vehicleId == null) ? 0 : vehicleId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Vehicle other = (Vehicle) obj;
		if (vehicleId == null) {
			if (other.vehicleId != null) {
				return false;
			}
		} else if (!vehicleId.equals(other.vehicleId)) {
			return false;
		}
		return true;
	}

}
