package com.example.dto;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ROUTE 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Route implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ROUTE_ID. */
	private Integer routeId;

	/** ROUTE_NAME. */
	private String routeName;

	/** START_LAT. */
	private String startLat;

	/** START_LNG. */
	private String startLng;

	/** START_ADDRESS. */
	private String startAddress;

	/** ARRIVE_LAT. */
	private String arriveLat;

	/** ARRIVE_LNG. */
	private String arriveLng;

	/** ARRIVE_ADDRESS. */
	private String arriveAddress;

	/** DISTANCE. */
	private String distance;

	/** TIME. */
	private String time;

	/** STEP 목록. */
	private Set<Step> stepSet;

	/**
	 * 생성자.
	 */
	public Route() {
		this.stepSet = new HashSet<Step>();
	}

	/**
	 * ROUTE_ID을 설정합니다..
	 * 
	 * @param routeId
	 *            ROUTE_ID
	 */
	public void setRouteId(Integer routeId) {
		this.routeId = routeId;
	}

	/**
	 * ROUTE_ID을 가져옵니다..
	 * 
	 * @return ROUTE_ID
	 */
	public Integer getRouteId() {
		return this.routeId;
	}

	/**
	 * ROUTE_NAME을 설정합니다..
	 * 
	 * @param routeName
	 *            ROUTE_NAME
	 */
	public void setRouteName(String routeName) {
		this.routeName = routeName;
	}

	/**
	 * ROUTE_NAME을 가져옵니다..
	 * 
	 * @return ROUTE_NAME
	 */
	public String getRouteName() {
		return this.routeName;
	}

	/**
	 * START_LAT을 설정합니다..
	 * 
	 * @param startLat
	 *            START_LAT
	 */
	public void setStartLat(String startLat) {
		this.startLat = startLat;
	}

	/**
	 * START_LAT을 가져옵니다..
	 * 
	 * @return START_LAT
	 */
	public String getStartLat() {
		return this.startLat;
	}

	/**
	 * START_LNG을 설정합니다..
	 * 
	 * @param startLng
	 *            START_LNG
	 */
	public void setStartLng(String startLng) {
		this.startLng = startLng;
	}

	/**
	 * START_LNG을 가져옵니다..
	 * 
	 * @return START_LNG
	 */
	public String getStartLng() {
		return this.startLng;
	}

	/**
	 * START_ADDRESS을 설정합니다..
	 * 
	 * @param startAddress
	 *            START_ADDRESS
	 */
	public void setStartAddress(String startAddress) {
		this.startAddress = startAddress;
	}

	/**
	 * START_ADDRESS을 가져옵니다..
	 * 
	 * @return START_ADDRESS
	 */
	public String getStartAddress() {
		return this.startAddress;
	}

	/**
	 * ARRIVE_LAT을 설정합니다..
	 * 
	 * @param arriveLat
	 *            ARRIVE_LAT
	 */
	public void setArriveLat(String arriveLat) {
		this.arriveLat = arriveLat;
	}

	/**
	 * ARRIVE_LAT을 가져옵니다..
	 * 
	 * @return ARRIVE_LAT
	 */
	public String getArriveLat() {
		return this.arriveLat;
	}

	/**
	 * ARRIVE_LNG을 설정합니다..
	 * 
	 * @param arriveLng
	 *            ARRIVE_LNG
	 */
	public void setArriveLng(String arriveLng) {
		this.arriveLng = arriveLng;
	}

	/**
	 * ARRIVE_LNG을 가져옵니다..
	 * 
	 * @return ARRIVE_LNG
	 */
	public String getArriveLng() {
		return this.arriveLng;
	}

	/**
	 * ARRIVE_ADDRESS을 설정합니다..
	 * 
	 * @param arriveAddress
	 *            ARRIVE_ADDRESS
	 */
	public void setArriveAddress(String arriveAddress) {
		this.arriveAddress = arriveAddress;
	}

	/**
	 * ARRIVE_ADDRESS을 가져옵니다..
	 * 
	 * @return ARRIVE_ADDRESS
	 */
	public String getArriveAddress() {
		return this.arriveAddress;
	}

	/**
	 * DISTANCE을 설정합니다..
	 * 
	 * @param distance
	 *            DISTANCE
	 */
	public void setDistance(String distance) {
		this.distance = distance;
	}

	/**
	 * DISTANCE을 가져옵니다..
	 * 
	 * @return DISTANCE
	 */
	public String getDistance() {
		return this.distance;
	}

	/**
	 * TIME을 설정합니다..
	 * 
	 * @param time
	 *            TIME
	 */
	public void setTime(String time) {
		this.time = time;
	}

	/**
	 * TIME을 가져옵니다..
	 * 
	 * @return TIME
	 */
	public String getTime() {
		return this.time;
	}

	/**
	 * STEP 목록을 설정합니다..
	 * 
	 * @param stepSet
	 *            STEP 목록
	 */
	public void setStepSet(Set<Step> stepSet) {
		this.stepSet = stepSet;
	}

	/**
	 * STEP를 추가합니다..
	 * 
	 * @param step
	 *            STEP
	 */
	public void addStep(Step step) {
		this.stepSet.add(step);
	}

	/**
	 * STEP 목록을 가져옵니다..
	 * 
	 * @return STEP 목록
	 */
	public Set<Step> getStepSet() {
		return this.stepSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((routeId == null) ? 0 : routeId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Route other = (Route) obj;
		if (routeId == null) {
			if (other.routeId != null) {
				return false;
			}
		} else if (!routeId.equals(other.routeId)) {
			return false;
		}
		return true;
	}

}
